apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-ops-log
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/kimgunwooo/platform-ops-log
    newTag: git-5dad0317a9f4
