apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/kimgunwooo/blog
    newTag: sha-bf03a583c1bb1c529eac9289cc3f95c78708e2ab
