apiVersion: v1
kind: Service
metadata:
  name: platform-ops-log
  labels:
    app.kubernetes.io/name: platform-ops-log
    app.kubernetes.io/part-of: platform-ops-log
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-ops-log
  ports:
    - name: http
      port: 4321
      targetPort: http
